sonar.projectKey=cc-aibd-09-reactnative-dawanapp
sonar.projectName=CC-AIBD-09 React Native DawanApp
sonar.sources=src,App.tsx
sonar.tests=src/__tests__
sonar.exclusions=node_modules/**,coverage/**,.expo/**,web-build/**,android/**,ios/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
