sonar.projectKey=cc-aibd-07-nodejs-cinemaapi
sonar.projectName=CC-AIBD-07 NodeJS CinemaAPI
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,uploads/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
